# Generated by Django 5.1 on 2024-09-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturi', '0002_alter_facturamodel_localitate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturamodel',
            name='tip_factura',
            field=models.CharField(choices=[('e-factura', 'e-factura'), ('factura-romana', 'Factura in romana'), ('factura-engleza', 'Factura in engleza'), ('factura-germana', 'Factura in germana'), ('factura-franceza', 'Factura in franceza'), ('factura-spaniola', 'Factura in spaniola')], default='e-factura', max_length=300),
        ),
    ]
