# Generated by Django 5.1 on 2024-09-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturi', '0004_facturamodel_valuta_alter_facturamodel_tip_factura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturamodel',
            old_name='fisier_efactura_pdf',
            new_name='fisier_factura_pdf',
        ),
        migrations.RemoveField(
            model_name='facturamodel',
            name='fisier_pdf',
        ),
    ]
