# Generated by Django 5.1 on 2024-09-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturi', '0005_rename_fisier_efactura_pdf_facturamodel_fisier_factura_pdf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturamodel',
            old_name='actualizat_la',
            new_name='data_inserarii',
        ),
    ]
