# Generated by Django 5.1 on 2024-09-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturi', '0006_rename_actualizat_la_facturamodel_data_inserarii'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='facturamodel',
            constraint=models.UniqueConstraint(fields=('serie', 'numar'), name='unique_serie_numar'),
        ),
    ]
